---
title: "Overall correlations summarized"
author: "Gavin Douglas"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    theme: cerulean
    toc: true
    toc_float: true
---

```{r setup}
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(ggbeeswarm))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(reshape2))
```

Overall correlations between:
1. Number of HGT events called
2. Phylogenetic distance / highest taxonomic level differ
3. Co-occurrence (based on several metrics)

```{r read_in}
pairwise_hgt <- read.table("/mfs/gdouglas/projects/water_mags/blast_output/pairwise_tally_summary.tsv.gz",
                           header = TRUE, sep = "\t", stringsAsFactors = FALSE, row.names = 1)

tip_dists <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaG_simple_cooccur.taxa_info.tsv",
                           header = TRUE, sep = "\t", stringsAsFactors = FALSE, row.names = 1)

cooccur <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaG_simple_cooccur.tsv.gz",
                      header = TRUE, sep = "\t", stringsAsFactors = FALSE)

tip_dists$simple_cooccur <- cooccur$simple_cooccur
```

```{r basic_plots}
intersecting_tip_dist_rows_i <- which(rownames(tip_dists) %in% rownames(pairwise_hgt))

pairwise_hgt <- pairwise_hgt[rownames(tip_dists)]

pairwise_hgt_subset <- pairwise_hgt[intersecting_taxa_combos, ]

pairwise_hgt_subset$tip_dist <- cooccur[intersecting_taxa_combos, "tip_dist"]
pairwise_hgt_subset$hyperg_cooccur <- cooccur[intersecting_taxa_combos, "tip_dist"]

```

```{r read_networks}
old_tip_dist <- read.table("/mfs/gdouglas/projects/water_mags/phylogenetic_analyses/tip_dist.tsv.gz", row.names = 1, header = TRUE, sep = "\t")

metaG_network <- list()
metaG_network[["hyperg_cooccur"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaG_hyperg_cooccur.taxa_info.tsv.gz",
                                                header=TRUE, sep = "\t", stringsAsFactors = FALSE)
metaG_network[["propr_rpkm"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaG_propr_rpkm.taxa_info.tsv.gz",
                                            header=TRUE, sep = "\t", stringsAsFactors = FALSE)
metaG_network[["simple_cooccur"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaG_simple_cooccur.taxa_info.tsv.gz",
                                                header=TRUE, sep = "\t", stringsAsFactors = FALSE)
metaG_network[["spieceasi_rpkm"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaG_spieceasi_rpkm.taxa_info.tsv.gz",
                                                header=TRUE, sep = "\t", stringsAsFactors = FALSE)

metaT_network <- list()
metaT_network[["hyperg_cooccur"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaT_hyperg_cooccur.taxa_info.tsv.gz",
                                                header=TRUE, sep = "\t", stringsAsFactors = FALSE)
metaT_network[["propr_rpkm"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaT_propr_rpkm.taxa_info.tsv.gz",
                                            header=TRUE, sep = "\t", stringsAsFactors = FALSE)
metaT_network[["simple_cooccur"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaT_simple_cooccur.taxa_info.tsv.gz",
                                                header=TRUE, sep = "\t", stringsAsFactors = FALSE)
metaT_network[["spieceasi_rpkm"]] <- read.table("/mfs/gdouglas/projects/water_mags/coverm/network_working/metaT_spieceasi_rpkm.taxa_info.tsv.gz",
                                                header=TRUE, sep = "\t", stringsAsFactors = FALSE)
```


# Overall scatterplots {.tabset}

## 
```{r hgt_by_phylo_dist}
rownames(metaG_network[["hyperg_cooccur"]]) <- paste(metaG_network[["hyperg_cooccur"]]$taxon_i, metaG_network[["hyperg_cooccur"]]$taxon_j, sep = ",")

intersecting_taxa_combos <- intersect(rownames(metaG_network[["hyperg_cooccur"]]), rownames(pairwise_hgt))
```

# Session info {.tabset}

## Hide

## Show

```{r show_info}
sessionInfo()
```
